branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: docs
          release: patch
        - type: style
          release: patch
        - type: refactor
          release: patch
        - type: chore
          release: patch
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 eslint-config changelog"
  - - "@semantic-release/npm"
    - npmPublish: false
      tarballDir: "false"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore(release): perform release ${nextRelease.version}"
