name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-yarn:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 18.18

      - name: Build
        run: |
          yarn --frozen-lockfile
